# Generated by Django 3.0.2 on 2020-01-04 02:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 1, 4, 2, 6, 15, 723377, tzinfo=utc)),
        ),
    ]
